import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  token = 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb3JyZWxhdGlvbmlkIjoiMEhNOFVRRDFFUUVJUjowMDAwMDAwMiIsInRlbmFudGlkIjoiMzhmNmQ0OTctOWU0MS00M2Q1LTg3NTctYTRkNGI2ZWExYjUwIiwib3JkZXJyZWYiOiJEQU5fT1JERVIiLCJpbnN0cnVjdGlvbnJlZiI6IkRBTl9JTlNUUlVDVElPTl83MCIsImN1c3RvbWVycmVmIjoiREFOIiwianRpIjoiMWRlM2YxNGYtZDE2OS00ZmUyLTg4ZmUtZWNlYzkyMDliYWIyIiwicm9sZSI6InRlbmFudC10cmFuc2FjdGlvbi1yZWFkIiwiYmlsbGluZ2NpdHkiOiJDaXR5IiwiYmlsbGluZ3N0YXRlIjoiU3RhdGUiLCJiaWxsaW5nY291bnRyeSI6IkdCIiwiYmlsbGluZ3N0cmVldDEiOiIxIFRlc3QgU3RyZWV0IiwiYmlsbGluZ3N0cmVldDIiOiJBbm90aGVyIFN0cmVldCIsImJpbGxpbmdwb3N0Y29kZSI6IjEyMyBBQkMiLCJjdXN0b21lcmVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImNhcmRob2xkZXJuYW1lIjoiTVIgVCBFU1QiLCJuYmYiOjE2MjU3NTM0NTQsImV4cCI6MTYyNTc1OTUxNCwiaXNzIjoiaHR0cHM6Ly9jaS1vcGVuaWQuaW1idXJzZS5uZXQvIiwiYXVkIjoiaHR0cHM6Ly9jaS1hcGkuaW1idXJzZS5uZXQvIn0.A3rB9bT10bHtw-uFXIJtfN-JmwRv5DpnoydDVAOkf1xARuDTlu7CA2rcSw7KEq3hVazrXtaU0z1qZEvF-ozLISAfslvI3xV-PEdDViH1Wi9ux0g_EfkNrchPRES01TZEKXrSuFl3FZbdtMGrFtzRey4XRKE4gx7iRsFAugjP7ztnbVOWFKy4laNZllIj2g4KFEf71xXHWtiBcDpH12W1BKk19IPAWAPdnXZaeh7pKdcz4qhAHhr9kwHM-vr1KJ_ot87mS9WDsEYvriishmPNEnAoJD9cEu3Fqwuq2wLpZjSxKp1e3KoAhXXZMGhb0xBZ0XpiZRAoUV39oo-ULLNaVQ';
  returnURL = 'http://localhost:4200'
}
